echo build image...
docker build -t nginx-react .
echo run start...
#up은 run하는 기능까지 포함
docker-compose -f /jenkins/workspace/frontend-build/gateway/docker-compose.yml up -d --force-recreate --no-deps react
docker image prune -f
