FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u292-b10 as builder
WORKDIR /app
COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
RUN \
chmod +x ./gradlew \
&& ./gradlew build \
|| return 0
COPY src ./src
RUN ./gradlew bootJar
FROM adoptopenjdk/openjdk8:x86_64-alpine-jre8u292-b10
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar ./app.jar
COPY /home/ubuntu/jjanhae.p12 ./
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
CMD ["--datasource.username=jjanhae", "--datasource.password=password"]
