echo mvn clean install -U ...
mvn clean install -U
cd docker/openvidu-server
echo create_image shell running...
./create_image.sh latest
cd /home/ubuntu/opt/openvidu
echo restart openvidu...
./openvidu restart