FROM adoptopenjdk/openjdk11:latest as builder
WORKDIR /app
# COPY build.gradle settings.gradle gradlew ./
# COPY gradle ./gradle
# RUN \
# chmod +x ./gradlew \
# && ./gradlew build \
# || return 0
COPY src ./src
COPY pom.xml ./pom.xml
CMD mvn clean install -U
# RUN ./gradlew bootJar
FROM adoptopenjdk/openjdk11:latest
WORKDIR /app
COPY --from=builder /app/build/libs/openvidu-server-2.20.0.jar ./openvidu.jar
EXPOSE 8443
ENTRYPOINT ["java", "-jar", "openvidu.jar"]